name: Make release

on:
  push:
    branches:
      - main
    paths:
      - CITATION.cff

env:
  GLOB: "{/data/STRchive-loci*.json,/data/STRchive-citations*.json,/data/STRchive-disease-loci*.bed}"

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Debug dump
        uses: crazy-max/ghaction-dump-context@v2

      - name: Checkout code
        uses: actions/checkout@v4

      - name: SSH debug
        if: runner.debug == '1'
        uses: mxschmitt/action-tmate@v3

      - name: Get previous version file
        run: git show HEAD~1:CITATION.cff >> CITATION-previous.cff

      - name: Install packages
        run: npm install yaml@v2 semver@v7 glob@v11

      - name: Get version and body
        id: version
        uses: actions/github-script@v7
        with:
          script: |
            return require('./.github/workflows/version.js')(${{ env.GLOB }});

      - name: Create GitHub release
        uses: ncipollo/release-action@v1
        if: ${{ steps.version.outputs.result }}
        with:
          commit: ${{ github.ref }}
          tag: v${{ steps.version.outputs.result }}
          name: v${{ steps.version.outputs.result }}
          draft: true
          artifactErrorsFailBuild: true
          artifacts:
            - ${{ env.GLOB }}
